// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: artifact/v1/image-repositories.proto

package artifact

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageRepositoriesServiceClient is the client API for ImageRepositoriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageRepositoriesServiceClient interface {
	List(ctx context.Context, in *ImageRepositoriesListRequest, opts ...grpc.CallOption) (*ImageRepositoriesListResponse, error)
	Create(ctx context.Context, in *ImageRepositoriesCreateRequest, opts ...grpc.CallOption) (*ImageRepositoriesResponse, error)
	Get(ctx context.Context, in *ImageRepositoriesGetRequest, opts ...grpc.CallOption) (*ImageRepositoriesResponse, error)
}

type imageRepositoriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageRepositoriesServiceClient(cc grpc.ClientConnInterface) ImageRepositoriesServiceClient {
	return &imageRepositoriesServiceClient{cc}
}

func (c *imageRepositoriesServiceClient) List(ctx context.Context, in *ImageRepositoriesListRequest, opts ...grpc.CallOption) (*ImageRepositoriesListResponse, error) {
	out := new(ImageRepositoriesListResponse)
	err := c.cc.Invoke(ctx, "/artifact.ImageRepositoriesService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageRepositoriesServiceClient) Create(ctx context.Context, in *ImageRepositoriesCreateRequest, opts ...grpc.CallOption) (*ImageRepositoriesResponse, error) {
	out := new(ImageRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/artifact.ImageRepositoriesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageRepositoriesServiceClient) Get(ctx context.Context, in *ImageRepositoriesGetRequest, opts ...grpc.CallOption) (*ImageRepositoriesResponse, error) {
	out := new(ImageRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/artifact.ImageRepositoriesService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageRepositoriesServiceServer is the server API for ImageRepositoriesService service.
// All implementations must embed UnimplementedImageRepositoriesServiceServer
// for forward compatibility
type ImageRepositoriesServiceServer interface {
	List(context.Context, *ImageRepositoriesListRequest) (*ImageRepositoriesListResponse, error)
	Create(context.Context, *ImageRepositoriesCreateRequest) (*ImageRepositoriesResponse, error)
	Get(context.Context, *ImageRepositoriesGetRequest) (*ImageRepositoriesResponse, error)
	mustEmbedUnimplementedImageRepositoriesServiceServer()
}

// UnimplementedImageRepositoriesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageRepositoriesServiceServer struct {
}

func (UnimplementedImageRepositoriesServiceServer) List(context.Context, *ImageRepositoriesListRequest) (*ImageRepositoriesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedImageRepositoriesServiceServer) Create(context.Context, *ImageRepositoriesCreateRequest) (*ImageRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedImageRepositoriesServiceServer) Get(context.Context, *ImageRepositoriesGetRequest) (*ImageRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedImageRepositoriesServiceServer) mustEmbedUnimplementedImageRepositoriesServiceServer() {
}

// UnsafeImageRepositoriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageRepositoriesServiceServer will
// result in compilation errors.
type UnsafeImageRepositoriesServiceServer interface {
	mustEmbedUnimplementedImageRepositoriesServiceServer()
}

func RegisterImageRepositoriesServiceServer(s grpc.ServiceRegistrar, srv ImageRepositoriesServiceServer) {
	s.RegisterService(&ImageRepositoriesService_ServiceDesc, srv)
}

func _ImageRepositoriesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRepositoriesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRepositoriesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifact.ImageRepositoriesService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRepositoriesServiceServer).List(ctx, req.(*ImageRepositoriesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageRepositoriesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRepositoriesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRepositoriesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifact.ImageRepositoriesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRepositoriesServiceServer).Create(ctx, req.(*ImageRepositoriesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageRepositoriesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRepositoriesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRepositoriesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifact.ImageRepositoriesService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRepositoriesServiceServer).Get(ctx, req.(*ImageRepositoriesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageRepositoriesService_ServiceDesc is the grpc.ServiceDesc for ImageRepositoriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageRepositoriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artifact.ImageRepositoriesService",
	HandlerType: (*ImageRepositoriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ImageRepositoriesService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ImageRepositoriesService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ImageRepositoriesService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artifact/v1/image-repositories.proto",
}
