// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: artifact/v1/repositories.proto

package artifact

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RepositoriesServiceClient is the client API for RepositoriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoriesServiceClient interface {
	List(ctx context.Context, in *RepositoriesListRequest, opts ...grpc.CallOption) (*RepositoriesListResponse, error)
	Create(ctx context.Context, in *RepositoriesCreateRequest, opts ...grpc.CallOption) (*RepositoriesResponse, error)
	Get(ctx context.Context, in *RepositoriesGetRequest, opts ...grpc.CallOption) (*RepositoriesResponse, error)
}

type repositoriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoriesServiceClient(cc grpc.ClientConnInterface) RepositoriesServiceClient {
	return &repositoriesServiceClient{cc}
}

func (c *repositoriesServiceClient) List(ctx context.Context, in *RepositoriesListRequest, opts ...grpc.CallOption) (*RepositoriesListResponse, error) {
	out := new(RepositoriesListResponse)
	err := c.cc.Invoke(ctx, "/artifact.RepositoriesService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoriesServiceClient) Create(ctx context.Context, in *RepositoriesCreateRequest, opts ...grpc.CallOption) (*RepositoriesResponse, error) {
	out := new(RepositoriesResponse)
	err := c.cc.Invoke(ctx, "/artifact.RepositoriesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoriesServiceClient) Get(ctx context.Context, in *RepositoriesGetRequest, opts ...grpc.CallOption) (*RepositoriesResponse, error) {
	out := new(RepositoriesResponse)
	err := c.cc.Invoke(ctx, "/artifact.RepositoriesService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoriesServiceServer is the server API for RepositoriesService service.
// All implementations must embed UnimplementedRepositoriesServiceServer
// for forward compatibility
type RepositoriesServiceServer interface {
	List(context.Context, *RepositoriesListRequest) (*RepositoriesListResponse, error)
	Create(context.Context, *RepositoriesCreateRequest) (*RepositoriesResponse, error)
	Get(context.Context, *RepositoriesGetRequest) (*RepositoriesResponse, error)
	mustEmbedUnimplementedRepositoriesServiceServer()
}

// UnimplementedRepositoriesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRepositoriesServiceServer struct {
}

func (UnimplementedRepositoriesServiceServer) List(context.Context, *RepositoriesListRequest) (*RepositoriesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRepositoriesServiceServer) Create(context.Context, *RepositoriesCreateRequest) (*RepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRepositoriesServiceServer) Get(context.Context, *RepositoriesGetRequest) (*RepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRepositoriesServiceServer) mustEmbedUnimplementedRepositoriesServiceServer() {}

// UnsafeRepositoriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoriesServiceServer will
// result in compilation errors.
type UnsafeRepositoriesServiceServer interface {
	mustEmbedUnimplementedRepositoriesServiceServer()
}

func RegisterRepositoriesServiceServer(s grpc.ServiceRegistrar, srv RepositoriesServiceServer) {
	s.RegisterService(&RepositoriesService_ServiceDesc, srv)
}

func _RepositoriesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoriesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoriesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifact.RepositoriesService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoriesServiceServer).List(ctx, req.(*RepositoriesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoriesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoriesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoriesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifact.RepositoriesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoriesServiceServer).Create(ctx, req.(*RepositoriesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoriesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoriesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoriesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/artifact.RepositoriesService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoriesServiceServer).Get(ctx, req.(*RepositoriesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepositoriesService_ServiceDesc is the grpc.ServiceDesc for RepositoriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepositoriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artifact.RepositoriesService",
	HandlerType: (*RepositoriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RepositoriesService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RepositoriesService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RepositoriesService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artifact/v1/repositories.proto",
}
